#+TITLE:      关于笔记的那些事儿
#+AUTHOR:     rgb-24bit
#+EMAIL:      rgb-24bit@foxmail.com
#+DATE:       <2018-06-17 周日>

* 目录                                                    :TOC_4_gh:noexport:
- [[#前言][前言]]
- [[#笔记的作用][笔记的作用]]
- [[#怎样做笔记][怎样做笔记]]
- [[#习惯很重要][习惯很重要]]
- [[#结语][结语]]

* 前言
  就在刚才， 我完成了每周例行一次的 *笔记收集清理*, 在一次感受到了部分现有笔记的混乱。

  心里很想去整理一下， 但准备做的时候又深感无力， 莫名的烦躁充满了全身。

  虽然真的要做的话， 工作量应该不大， 但主要的工作都是对现有内容的剪切， 分类等。 

  枯燥， 缺少动力。

  看了一下其他部分做的比较好的笔记， 突然发现， 这些比较好的笔记是在一开始就做的比较好的， 而不好的那一部分，
  一开始也没认真记录。

  回忆了一下整个笔记的记录过程， 感觉有必要记录下来， 在之后警示自己。

* 笔记的作用
  经常听到的一个问题就是： *为什么要做笔记 ？*

  这个问题问的就是 *笔记的作用*, 笔记有什么用， 我为什么做笔记， 做了笔记我能有什么收获， 有什么好处......

  我开始记笔记的时候也想过这些问题， 但没有得到答案， 只是单纯的觉得记笔记可能会有帮助， 便开始记笔记了。

  现在回过头来， 发现笔记的用处大概就是让我在忘了什么东西的时候， 能够快速的从笔记中找到解决方案。

  毕竟， 笔记的作用不是然你记住那些东西， 而是把那些东西放在一个你更容易找到的地方。

* 怎样做笔记 
  怎样做笔记是一个很重要的问题， 这影响到你做的笔记是否能够发挥它的作用。

  首先， 需要明白的是， 笔记是为了能够让你快速从中找到某个问题的解决方案。

  如果， 你的笔记系统混乱， 不堪入目， 相信我， 你不会想打开笔记的。

  因此， 你需要一个 *笔记系统*, 通过这个系统， 完成 *收集*, *整理* 的过程。

  + 收集阶段将需要记录的内容收集起来， 如果是博客那么可以将链接记录下来， 如果是书上的内容， 那么可以将页码记录下来
  + 整理阶段将收集的内容扩展整理， 根据你笔记系统的结构将它们记录到合适的位置

  当然， 我还喜欢加上一个 *消化* 的过程：
  + 将笔记中相似相关的部分内容汇总整理， 理解， 消化， 然后写一篇博客， 算是将笔记的保存位置转移到另一个
    地方。 但是经过这个过程能够加深对相关内容的理解， 积累。

  个人认为 *消化* 是一个很有必要的阶段， 当然消化的方式可以看个人爱好， 但是如果不消化的话， 你记的笔记的最大可能就是
  被丢在一个角落生灰， 哪怕之后遇到的问题就在你的笔记里面， 你都不知道。

  在多说一句， 在我看来， 笔记的主要作用就是 *记录*, 但是记录了的东西不代表就是你的了， 因此， 还需要通过 *消化* 来进行 *积累*.

  那么这三个阶段最重要的是哪个阶段呢 ？

  最开始， 我觉得是 *整理* 阶段， 因为如果不整理的话， 那么 *收集* 就没有作用。

  后来觉得是 *消化* 阶段， 因为如果不消化的话， 那么 *整理* 就没有价值。

  现在， 我觉得是最重要的是 *收集* 阶段， 因为如果收集做的不好， 那么后面的工作都将无用。

  记得以前听到过的一句话： 记笔记有什么用呢 ？ 记了不一定记得好， 记得好也不一定会看。

  当时觉得这句话挺有道理的， 现在的话， 不对。

  实际的情况应该是： 笔记记得好， 总有用到它的时候， 笔记记得不好， 你记再多也没有用。

  就我目前来说， 打开笔记后， 会下意识的回避哪些记得不好的笔记， 不是它们的内容没有用， 而是本能的想回避这些东西。

  就像开篇说的， 我发现所有记得比较好的笔记都有一个共同的特点： *一开始就做的足够好*.

  用物理学上的原理来解释的话： 一个封闭系统的混乱程度 - 熵会不断增加， 除非你为这个系统注入了新的能量。

  然后， 事实就是， 我们这个世界是科学的， 如果你的笔记一开始就不够好， 除非你愿意话更多的时间和精力进行整理， 否则， 它只会
  越来越差。

  怎样在开始阶段 - *收集* 就做好呢 ？

  说实话， 我也没有什么经验， 但记了这么久的笔记， 我觉的还是可以分享一下个人见解：
  + 规范有序的收集过程 :: 通过规范而有序的收集需要记录的内容， 相信我， 这会让你在 *整理* 与 *消化* 的工作量
                 更少。 也会让你更有动力去整理， 而不是将收集的东西去掉， 然后告诉自己， 少记点没什么。

  + 不要只是 Copy & Paste :: 虽然很多笔记是对现有内容的拷贝， 但是不要什么内容都只是 ~Copy~ 和 ~Paste~. 如果
       只是靠 ~Copy~ 和 ~Paste~ 就能完成的工作， 还不如建立一个条目收集指向源的链接。 相信我， 简单 ~Copy~ 和 ~Paste~
       得到的内容还不如看原有内容好。

  + 一定要有收集的过程 :: 其实很多内容在看的时候， 你就会发现， 这些内容似乎可以直接放到 *笔记*, 而不是放到 *收集箱*.
                 因此你选择了将它们直接放入 *笔记*.

                 但是这样做带来的好处不是很多， 但带来的损失可能更多。 因为在边看边记的过程中， 分心进行记录的话，
                 容易让你失去整个阅读过程的流畅感， 也无法保证你现在记录的内容的质量。

                 *收集* 到 *整理* 是一个缓冲的过程， 通过这个过程， 能够让你将更多的精力放在笔记的整理上， 而不是关心 *我该记什么*.

* 习惯很重要
  记笔记最重要的是什么， 我觉得是 *方法* 和 *习惯*.

  方法前面说过了， 另一个就是习惯。 记笔记的习惯。

  高中的数学老师说过一句话： *优秀是一种习惯*.

  当时不太理解， 现在感觉这句话真的很有道理， 因为优秀的人会在一件事开始的时候， 就习惯性的想要做好它。

  对于一个好习惯的重要性我就不多说了， 鸡汤喝的再多， 不去实践终究会原封不动的排出去。

  如果你想记笔记了， 请尝试尽可能的坚持一段时间， 然后， 在慢慢优化改进自己的笔记系统。

  到时候， 你会发现， 记笔记只是一种习惯， 我们需要做的只是在记笔记时记好， 而不是去考虑需不需要做笔记的问题。

* 结语
  作为一个程序员， 身处这个技术发展日新月异的时代， 深感无力。

  因为明白一点， 在这个时代， 你不进步， 那么你已经退步了。 因为有很多人正快速的赶超你。

  有时真的羡慕那些天赋好的人， 花更少的时间， 做到更多的事情。 最重要的是， 他们也在努力。

  笔记是一种手段， 提高自己， 不让自己落后太多的手段。

  共勉 (｀・ω・´)

